### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by latigreplata** [ottopaulsen/MMM-WeConnect#1]
First of all: Great idea for a really useful module!

I'm having a little problem; I copied your config.js-example  into my own config.js and changed the login credentials. However, I'm getting the following error message:

**MMM-WeConnect: Error logging in weconnect:  weconnect: Failed to log in. Wrong password. TypeError: Cannot read property '1' of null**

What I've tried so far:
-I've logged into both car-net and the new weconnect webpages and retried the module. No luck
-I updated MagicMirror and NPM. No luck

Any advise? Are there any types of characters in password not supported by module?

**Comment by ottopaulsen** [comment]
Hi. Nice you like it. I am experiencing errors from time to time. Often the We Connect service seems to be down. Other times I think there is a problem in my code. I do not have the time to look into this right now. 

Your config is good when you get this message. The error comes during the login process, and it is the login that fails. Did you download my latest changes? I did some improvements lately, but I see strange things from time to time.

I dont know how special characters work, but that may be a case. I just know that @ works fine.

Please let me know if you find out something.

**Comment by ottopaulsen** [comment]
I just uploaded some changes. Could you please download the new version and try again?
Be aware that the We Connect service is down pretty often, like yesterday night it was down for hours. However, today it is working fine.

Please let me know how it goes.

**Comment by latigreplata** [comment]
Updated and tested. Now the visual car says "Driving.." even though the car is parked (hopefully.. :P )

Console says the following:
MMM-WeConnect:  weconnect: Failed to log in. Wrong password. TypeError: Cannot read property '1' of null
Error logging in to We Connect:  Cannot log in to We Connect
[ 'Sending data: ',
  Map {
    'magicMirrorOnline' => true,
    'apiConnection' => { label: 'API Connection', value: 'ERROR', suffix: '' } } ]

**Comment by latigreplata** [comment]
I will try again later today

**Comment by latigreplata** [comment]
Now I get "Socket hangup". Could it mean some firewall issue?

`MMM-WeConnectRetrying
[ 'MMM-WeConnect: Logging in to WeConnect (3)' ]
MMM-WeConnect:  weconnect: Failed to log in. Wrong password. TypeError: Cannot read property '1' of null
Error logging in to We Connect:  Cannot log in to We Connect
[ 'Sending data: ',
  Map {
    'magicMirrorOnline' => true,
    'apiConnection' => { label: 'API Connection', value: 'ERROR', suffix: '' } } ]
MMM-WeConnect:  { RequestError: Error: socket hang up
    at new RequestError (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promise-core/l                                                   ib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promi                                                   se-core/lib/plumbing.js:46:31)
    at self.callback (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketOnEnd (_http_client.js:426:9)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  message: 'Error: socket hang up',
  cause:
   { Error: socket hang up
       at createHangUpError (_http_client.js:323:15)
       at TLSSocket.socketOnEnd (_http_client.js:426:23)
       at TLSSocket.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1103:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' },
  error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:323:15)
       at TLSSocket.socketOnEnd (_http_client.js:426:23)
       at TLSSocket.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1103:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' },
  options:
   { jar: RequestJar { _jar: [CookieJar] },
     headers:
      { Accept:
         'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'User-Agent':
         'Mozilla/5.0 (Linux; Android 6.0.1; D5803 Build/23.5.A.1.291; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36',
        Referer:
         'https://identity.vwgroup.io/signin-service/v1/b7a5bb47-f875-47cf-ab83-2ba3bf6bb738@apps_vw-dilab_com/login/identifier',
        'X-CSRF-Token': 'acqFXbW9',
        'Content-Length': 214 },
     uri:
      'https://identity.vwgroup.io/signin-service/v1/signin/b7a5bb47-f875-47cf-ab83-2ba3bf6bb738@apps_vw-dilab_com?relayState=7b85775cf9b315082a6780848663a519c48a02f3',
     resolveWithFullResponse: true,
     followAllRedirects: true,
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
  response: undefined }
`

**Comment by ottopaulsen** [comment]
Hi, and thanks for the feedback.

Socket hangup was new to me. 
But tonight mine is also failing, with the login failure error, but I cannot log in to the We Conenct web page either, and then the MM module will not work.
When you get that error, please check if you can log in on their web portal.

**Comment by latigreplata** [comment]
Yeah I see the site is even down for maintenance now. Will keep trying

**Comment by ottopaulsen** [comment]
Is tvis working for you? If nor, try the latest version, and try to log in manually ffom a normal browser to answer any consent questions.
