### ISSUE TITLE
Unable to verify first certificate

### ISSUE THREAD

**Issue by Paultie** [ottopaulsen/MMM-WeConnect#2]
I just reinstalled my setup and started using the WeConnect module. I like the idea and hoping that it will work.
I am getting the following error.
I have allready tried to set the ssl stric npm setting to false but this did not help.
hope thi can be fixed.

thanks

MMM-WeConnect:  { RequestError: Error: unable to verify the first certificate
    at new RequestError (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-WeConnect/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  message: 'Error: unable to verify the first certificate',
  cause:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
       at TLSSocket.emit (events.js:182:13)
       at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  error:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
       at TLSSocket.emit (events.js:182:13)
       at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  options:
   { jar: RequestJar { _jar: [CookieJar] },
     uri:
      'https://www.portal.volkswagen-we.com/portal/nl_NL/web/guest/home',
     resolveWithFullResponse: true,
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
  response: undefined }
MMM-WeConnectRetrying

**Comment by ottopaulsen** [comment]
I am having the same problem myself. Has been for a few weeks now. Not sure how to solve it, and I am not sure when I will get time to look at it.

**Comment by Paultie** [comment]
It seems to be certificate related by the looks of it. So I am not sure how you dealt with the certificates before....
Happy to investigate further but I am a novice in programming.

**Comment by fjdude** [comment]
@ottopaulsen : Please look at this problem.
This is the most important module for my magicmirror project.

**Comment by ottopaulsen** [comment]
I think I solved this for now, by ignoring the certificate warning.
Download he latest version and try.

If it does not work, try to log in manually from a browser. I recently got a consent question that disturbed the login procedure. Once that was answered, the module worked.

**Comment by Paultie** [comment]
This worked for me. Thanks for making this work around!
Not sure if you want to keep this issue open?

**Comment by ottopaulsen** [comment]
Good to hear.
